### ISSUE TITLE
TypeError: reselectPrevious is not a function

### ISSUE THREAD

**Issue by NeelDsouza** [sudodoki/copy-to-clipboard#105]
I'm getting this error while simulating the onClick functionality. 
```
TypeError: reselectPrevious is not a function
    at copy (node_modules\copy-to-clipboard\index.js:72:5)
    at Object.onClick (src\TableMenu/TableMenu.jsx:19:43)
    at Context.<anonymous> (src\TableMenu/TableMenu.test.js:62:62)
    at process.topLevelDomainCallback (domain.js:121:23)
```

**Menu.jsx**
```
import copy from 'copy-to-clipboard';

const TableMenu = ({onClick, onHide, rowId}) => (
    <MenuPopover
        onClick={onClick}
        onHide={onHide}>
        <MenuPopover.Item id={1} onClick={() => copy(rowId)} label='Copy'/>
    </MenuPopover>
);
```
**Menu.test.js**
```
import copy from 'copy-to-clipboard';
jest.mock('copy-to-clipboard', () => sinon.spy());

it('check method onCopy called', () => {
    const wrapper = shallow(<TableMenu {...props}/>);
    wrapper.find(MenuPopover.Item).last().props().onClick()
    expect(copy.calledOnce).to.eql(true);
});
```

**Comment by sudodoki** [comment]
can you verify `toggle-selection` package is installed? It's odd that `reselectPrevious` is not a function, if no exepctions occured during call to main fn https://github.com/sudodoki/toggle-selection/blob/gh-pages/index.js for storing selection

**Comment by cedricdelpoux** [comment]
The same occurred to me. `toggle-selection` package is installed and in my `nodes_modules`

**Comment by cedricdelpoux** [comment]
Ok I get it. This package does not work with nodeJS

**Comment by sudodoki** [comment]
@NeelDsouza can it be that you are having this code run in browserless environment? Gonna close it for now
